[book]
authors = ["Nikita Igumnov"]
language = "en"
multilingual = false
src = "2022-2023/src"
title = "Algorithms and Data Structures"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/NikitaChampion/Data-Structures"
